apiVersion: apps/v1beta1
kind: Deployment #application should goes to this
metadata:
  name: azure-vote-back 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - name: azure-vote-back #here is the real worker
        image: redis 
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service # this will open to public as a unit
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - name: azure-vote-front
        image: microsoft/azure-vote-front:v1
        ports:
        - containerPort: 80
        env:   # requirement
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer #specify the type so that interal resource could be balanced
  ports:
  - port: 80
  selector:
    app: azure-vote-front